# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e5fe69b70af6b860364047b4790c37b762ab7c6fb8bebd025c2c250a148fd2f6f66052f35126733b90bc4c84b916ab0d7f610e847a8afca62f0775b1355159a

test:
  secret_key_base: b894e8ce5ae1f03e1af5d93b9371a27d2be2c9a571b93e5cc10d7250cba75908516f144acf5450c726e00718305305e3994950a620d307e410d2c5586805f547

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
